services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: planner-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=planner
    ports:
      - 5432:5432
